### ISSUE TITLE
[Bug Report] v4.2.0 doesn't start with Linux

### ISSUE THREAD

**Issue by Vaasgeet** [TheOtherRolesAU/TheOtherRoles#414] opened 2022-10-28 18:06 UTC
I just updated my The Other Roles version to v4.2.0 and updated Among Us to the latest release version available on Steam. Unfortunately The Other Roles won't start at all. I've been waiting for more than 10min, but still not a single frame.

Once i remove the winhttp.dll from proton winecfg, Among Us boots up as expected.
Also reinstalling didn't work our for me, nether did deleting the compatdata folder. Is there any way to get some error logs?

![Bildschirmfoto vom 2022-10-28 19-45-22](https://user-images.githubusercontent.com/29280203/198703144-17cff978-5fcd-4f6f-80db-37cb7ecd2f1c.png)

System:
OS: Pop!_OS 22.04 LTS x86_64
Kernel: 6.0.2-76060002-generic
Among Us Version: v2022.10.25s
TheOtherRoles: v4.2.0

**Comment by chrisvannooten** [comment] 2022-10-29 20:29
Can confirm as of v4.2.0 the modpack fails to even start while the base game loads fine.
Among Us Version: v2022.10.25s
Tested on Ubuntu 22.04.1 LTS with Proton Experimental, Hotfix, 7.0-4 and 6.3-8.
The closest I could find to a reason in the terminal is:
wine: Call from 7BC321D0 to unimplemented function KERNEL32.dll.RaiseFailFastException, aborting
wine: Unimplemented function KERNEL32.dll.RaiseFailFastException called at address 7BC321D0 (thread 0150), starting debugger...

[RaiseFailFastException](https://learn.microsoft.com/en-us/windows/win32/api/errhandlingapi/nf-errhandlingapi-raisefailfastexception) is a pretty heavy function that by passes all exception handlers and ironically whatever calls it can't call it because it doesn't seem to be implemented in Wine. Both TheOtherRoles and BepInEx do not have any sign of using it. 
I assume it is being thrown because a requirement is not being met somewhere down the line.

**Comment by gendelo3** [comment] 2022-10-30 15:53
I am pretty sure this is due to BepInEx using CoreCLR now. With the development console enabled it states that Wine 7.16 or higher must be used, which apparently is not integrated with proton yet.

**Comment by shaoiken** [comment] 2022-11-01 10:49
Can confirm @gendelo3 the game doesn't run modded with latest proton but with wine 7.19-staging for me.

**Comment by Rahim407** [comment] 2022-11-02 18:09
@shaoiken how can i run game via steam with wine 7.19

**Comment by emiltoacs** [comment] 2022-11-04 16:41
I also have the same issue trying to run the game with Proton Experimental, 7.0.4, and 6.3.8

In the terminal I can see the same error as @chrisvannooten about KERNEL32.dll.RaiseFailFastException

@shaoiken  how did you run the game with wine ? I would like to try also 

Among Us Version: v2022.10.25s
TheOtherRoles: v4.2.0
Arch Linux with kernel: 6.0.6-arch1-1

**Comment by shaoiken** [comment] 2022-11-05 02:05
I installed wine-staging (https://wiki.winehq.org/Download) and used 'winetricks steam' (https://wiki.winehq.org/Winetricks) to install Steam running with wine and then just run Among Us modded with that Steam instance.

**Comment by emiltoacs** [comment] 2022-11-05 12:43
Thanks I can start Among Us the other role with the Window version of steam started with wine 7.20 staging and the winhttp native override trick. However once in game there is a lot of bug due to CoreCLR.  

Example when trying to change form as the shapeshifter the game crashes due to this error:
```
011c:err:eventlog:ReportEventW L"Application: Among Us.exe
CoreCLR Version: 6.0.722.32202
NET Version: 6.0.7
Description: The process was terminated due to an internal error in the .NET Runtime at IP 0ADD4572 (0AC10000) with exit code c0000005."
```
Which is from the description of this exception code c0000005 caused by the access denied that means the program is accessing a memory address without the permission.

There is many other bugs and the output is full of warning and fixme messages. There are many other situations where the game crash with exit code c0000005.

**Comment by gendelo3** [comment] 2022-11-07 06:59
We can't really give support with that for now. Linux support is not our priority, but BepInEx or wine will hopefully fix the issues at some point.

It may be worth opening an issue at BepInEx's repository, maybe they have now ideas for workarounds.

 I will leave this issue open.

**Comment by miniduikboot** [comment] 2022-11-12 17:27
Unfortunately the version of BepInEx used by TOR crashes on old versions of Wine on first launch and while playing. The fix for this was included in Wine 6.16 but has not yet made it into Proton, [although I've opened a PR](https://github.com/ValveSoftware/wine/pull/162)

For Steam, you can either compile the branch my PR is based on, convince an uncle that works at Valve to merge that PR or [download my precompiled version](https://mini.duikbo.at/proton-7.0-4-bepinex.tar.xz)

For the Itch/Epic versions, you can install Wine 6.16 or higher and run the game via that, unfortunately for the Steam version that's not an option.

**Comment by homeworkprod** [comment] 2022-11-13 09:59
Thanks!

But is it Wine 6.16 (as stated in your comment here) or Wine 7.16 (as stated in the PR against Valve's Wine)?

**Comment by miniduikboot** [comment] 2022-11-13 10:13
Sorry, I meant Wine 7.16 and have changed my comment accordingly

**Comment by ChristianKreuzberger** [comment] 2022-11-22 19:38
@miniduikboot Good job! Let's hope valve merges the change :)

**Comment by bluegreensea** [comment] 2022-12-05 16:18
I encounter the "Unable to run under proton more than once" issue
[LogOutput.log](https://github.com/TheOtherRolesAU/TheOtherRoles/files/10155895/LogOutput.log)
(delete BepInEx/interop will work again once)

**Comment by botmaker69** [comment] 2022-12-22 16:20
i coulda removed it from winecfg instead??? I been reinstalling the whole game since it works first run with winhttp in winecfg

**Closed** 2023-03-05 01:45 UTC
Labels: 🥴 bug
